/** Cartographic Editorial: merchant identity settings retain the current profile update and session behavior through the Node API. */
import { FormEvent, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, LogOut, Mail, Save, UserRound } from "lucide-react";
import { toast } from "sonner";
import { BrandMark } from "@/components/BrandMark";
import { useAuth } from "@/hooks/useAuth";
import { profileApi } from "@/lib/api";

export default function MerchantProfile() {
  const navigate = useNavigate();
  const { user, loading, signOut } = useAuth();
  const [displayName, setDisplayName] = useState("");
  const [saving, setSaving] = useState(false);
  useEffect(() => { if (!loading && !user) navigate("/merchant/auth"); }, [loading, user, navigate]);
  useEffect(() => { if (user) { setDisplayName(user.user_metadata.display_name || ""); profileApi.get().then(({ profile }) => profile?.display_name && setDisplayName(profile.display_name)).catch(() => undefined); } }, [user]);
  if (loading || !user) return <main className="grid min-h-screen place-items-center bg-[#102a31]"><div className="h-8 w-8 animate-spin rounded-full border-2 border-[#72d2c7] border-t-transparent" /></main>;
  const submit = async (event: FormEvent) => { event.preventDefault(); try { setSaving(true); await profileApi.update({ display_name: displayName }); toast.success("Profile updated"); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to update profile"); } finally { setSaving(false); } };
  return <main className="contour-surface min-h-screen p-5 sm:p-8"><div className="mx-auto max-w-4xl"><header className="flex items-center justify-between"><Link to="/merchant" className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground hover:text-primary"><ArrowLeft className="h-3.5 w-3.5" />Merchant desk</Link><button onClick={() => { signOut(); navigate("/"); }} className="inline-flex items-center gap-2 text-xs font-extrabold text-muted-foreground hover:text-destructive"><LogOut className="h-3.5 w-3.5" />Sign out</button></header><section className="mt-8 border border-border bg-card p-6 shadow-elevated sm:p-9"><div className="flex flex-wrap items-start justify-between gap-6 border-b border-border pb-7"><div className="flex items-center gap-4"><BrandMark className="h-14 w-14" /><div><p className="atlas-label text-primary">Merchant identity</p><h1 className="mt-1 font-display text-4xl tracking-[-0.05em]">Your account settings</h1></div></div><span className="border border-primary/20 bg-primary/5 px-3 py-2 font-mono text-[9px] uppercase tracking-[0.14em] text-primary">Owner access</span></div><form onSubmit={submit} className="mt-8 max-w-xl"><label className="block"><span className="atlas-label text-muted-foreground">Public display name</span><span className="mt-2 flex items-center gap-3 border border-border bg-background px-3 py-3 focus-within:border-primary"><UserRound className="h-4 w-4 text-primary" /><input required value={displayName} onChange={(event) => setDisplayName(event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none" /></span></label><label className="mt-5 block"><span className="atlas-label text-muted-foreground">Account email</span><span className="mt-2 flex items-center gap-3 border border-border bg-muted/40 px-3 py-3"><Mail className="h-4 w-4 text-muted-foreground" /><input disabled value={user.email} className="min-w-0 flex-1 bg-transparent text-sm font-semibold text-muted-foreground outline-none" /></span></label><p className="mt-4 text-xs leading-5 text-muted-foreground">Your display name is shown within the merchant desk. This email is your account identity and cannot be changed here.</p><button disabled={saving} className="mt-7 inline-flex items-center gap-2 bg-secondary px-4 py-3 text-sm font-extrabold text-secondary-foreground hover:bg-primary disabled:opacity-60"><Save className="h-4 w-4" />{saving ? "Saving…" : "Save profile"}</button></form></section></div></main>;
}
